name : AliBuild

on: [push]

jobs:
  aliBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Run Cowsay
      - run: |
            sudo apt-get install cowsay
            cowsay "Hello World"

